# Linear algebra

In [1]:
import numpy as np 

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,2],[2,6,5],[1,2,4]])
C1 = np.zeros((A.shape[0],B.shape[1]))


C3 = [] # list of rank 1 matrices
for a in range(A.shape[1]):
    C3.append(np.outer(A[:,a],B[a,:]))

for m in C3:
    print(m)
    if (m == C3[-1]).all():
        print('=')
    else:
        print('+')
print(sum(C3))


[[ 1  2  2]
 [ 4  8  8]
 [ 7 14 14]]
+
[[ 4 12 10]
 [10 30 25]
 [16 48 40]]
+
[[ 3  6 12]
 [ 6 12 24]
 [ 9 18 36]]
=
[[ 8 20 24]
 [20 50 57]
 [32 80 90]]
